remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme

title: Гварамадзе Роман
description: SEO • ML • NLP • RAG

collections:
  seo:
    output: true
    permalink: /seo/:name/

header_pages:
  - seo.md
